### ISSUE TITLE
python-gflags-2.0 test failures; py2.7, pypy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/python-gflags#15]
```
What steps will reproduce the problem?
1. Run testsuite under py2.7, pypy
2.
3.

What is the expected output? What do you see instead?
Pass.
Failures

What version of the product are you using? On what operating system?
python-gflags-2.0

Please provide any additional information below.

>>> Source compiled.
 * pypy1_9: running distutils-r1_run_phase python_test OR pypy2_0
.......F...F.
======================================================================
FAIL: testFlagHelpInXML_SpaceSeparatedList 
(__main__.WriteFlagHelpInXMLFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gflags_helpxml_test.py", line 253, in testFlagHelpInXML_SpaceSeparatedList
    self._CheckFlagHelpInXML('dirs', 'tool', expected_output)
  File "gflags_helpxml_test.py", line 102, in _CheckFlagHelpInXML
    self.assertMultiLineEqual(sio.getvalue(), expected_output)
  File "/mnt/gen2/TmpDir/portage/dev-python/python-gflags-2.0/work/python-gflags-2.0/tests/gflags_googletest.py", line 104, in assertMultiLineEqual
    unittest.TestCase.assertMultiLineEqual(self, expected, actual)
AssertionError: " <flag>\n   <file>tool</file>\n   <name>dirs</name>\n   
<meaning>Directories to [truncated]... != " <flag>\n   <file>tool</file>\n   
<name>dirs</name>\n   <meaning>Directories to [truncated]...
   <flag>
     <file>tool</file>
     <name>dirs</name>
     <meaning>Directories to search.</meaning>
     <default>src libs bin</default>
     <current>['src', 'libs', 'bin']</current>
     <type>whitespace separated list of strings</type>
-    <list_separator>' '</list_separator>
     <list_separator>'\t'</list_separator>
     <list_separator>'\n'</list_separator>
-    <list_separator>'\r'</list_separator>
     <list_separator>'\x0b'</list_separator>
     <list_separator>'\x0c'</list_separator>
+    <list_separator>'\r'</list_separator>
+    <list_separator>' '</list_separator>
   </flag>


======================================================================
FAIL: testWriteHelpInXMLFormat (__main__.WriteHelpInXMLFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gflags_helpxml_test.py", line 527, in testWriteHelpInXMLFormat
    self.assertMultiLineEqual(actual_output, expected_output)
  File "/mnt/gen2/TmpDir/portage/dev-python/python-gflags-2.0/work/python-gflags-2.0/tests/gflags_googletest.py", line 104, in assertMultiLineEqual
    unittest.TestCase.assertMultiLineEqual(self, expected, actual)
AssertionError: '<?xml version="1.0"?>\n<AllFlags>\n  
<program>gflags_helpxml_test.py</program>\ [truncated]... != '<?xml 
version="1.0"?>\n<AllFlags>\n  <program>gflags_helpxml_test.py</program>\ 
[truncated]...
Diff is 5042 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 13 tests in 0.041s

FAILED (failures=2)

dev-python/python-gflags $ PYTHON_TARGETS="python2_7" ebuild  
python-gflags-2.0.ebuild clean test

yields

>>> Source compiled.
 * python2_7: running distutils-r1_run_phase python_test
.............
----------------------------------------------------------------------
Ran 13 tests in 0.015s

OK
.........E......EEEWarning: Hit circular flagfile dependency: 
/mnt/gen2/TmpDir/portage/dev-python/python-gflags-2.0/temp/python2.7/gflags_unit
testuxxTfV/UnitTestFile3.tst
EEEEE..E.EEF.........
======================================================================

Log attached for py2.7
```

Original issue reported on code.google.com by `del...@iinet.com.au` on 4 Jul 2013 at 2:26

Attachments:
- [python-gflags-2.0_build.log](https://storage.googleapis.com/google-code-attachments/python-gflags/issue-15/comment-0/python-gflags-2.0_build.log)

**Comment by gpshead** [comment]
python-gflags users should migrate to absl-py:
 https://github.com/abseil/abseil-py
 https://pypi.python.org/pypi/absl-py/

It is the modern version of this library.
